### ISSUE TITLE
Basalt in campaign

### ISSUE THREAD

**Issue by Dragonbonded** [Slava0135/reFine#1]
I have not been able to find any basalt in the first 2 campaign maps, Ground Zero and Frozen Forest. 

On a completely unrelated note, Ground Zero can be beaten using just the player ship, and Frozen Forest requires Ground Zero and the Router.

Also, not sure what your planning to do with the sulfer and acid.

Possibly allow the furnace to function when placed on magma tiles (of which GZ has), and place miners on rock, mining out basalt.

**Comment by Slava0135** [comment]
> I have not been able to find any basalt in the first 2 campaign maps, Ground Zero and Frozen Forest.
> 
> On a completely unrelated note, Ground Zero can be beaten using just the player ship, and Frozen Forest requires Ground Zero and the Router.
> 
> Also, not sure what your planning to do with the sulfer and acid.
> 
> Possibly allow the furnace to function when placed on magma tiles (of which GZ has), and place miners on rock, mining out basalt.

I haven't touched this mod in ages, I don't really support it because I don't think it was a great idea. If you have ideas on how to improve the mod the I will consider them though.

**Comment by Dragonbonded** [comment]
A simple-ish mod that adds in an additional stage for various ores i think is fun. Its not super complicated, and kinda straightforwards, in both idea and scope.

If you can get the naturally spawning basalt to work, that would be best. Alternatively, with basalt being a volcanic material, you could make it minable from the cracked magma tiles (the ones you put the thermal generators on).

As far as the furnaces, having the base one use said cracked magma tiles in place of coal, with the electric furnace using, well, power, should be best. 

The electric variant should be twice as powerful in some way.... maybe output 2 ingots per 1 ore, due to more efficient processing?

For the acid/sulfur, unless youve got something planned for that, i say drop it. If you do, creating the liquid "acid" via water and sulfur should work. 

If pools of liquid (such as from an open pipe) can do things, i suggest making it deal damage to any unit or building it touches. 

If not, making it a DOT ammunition for the wave turret (and similar) should be entertaining, and quite feasible, considering its acid, not poison.

Edit:apparently there's a "reply to" button i missed somewhere

**Comment by Slava0135** [comment]
No need to reply actually as I get notified anyways. I will try to improve on stuff you have mentioned tho I am not sure when I will do so. Maybe in a week? We will see.

**Comment by Dragonbonded** [comment]
> No need to reply actually as I get notified anyways. I will try to improve on stuff you have mentioned tho I am not sure when I will do so. Maybe in a week? We will see.

Totally fine. fixing the basalt spawn and making acid a liquid being useful in liquid turrets is the bare minimum im asking for.

You wanted ideas, so i shared a few. Just keep in mind that Ground Zero doesnt have any coal. I hate that fact.

**Comment by Slava0135** [comment]
I made new version for v7.
It makes acid to double the output per ore for Electric Furnace (as optional input)

**Comment by Slava0135** [comment]
If you have feedback - open a new issue
